baseURL = "https://pukaraes.github.io"
DefaultContentLanguage = "es"
title = "Pukara"
[languages]
    [languages.es]
        languageName = "es"
        baseURL = "https://pukara.es/"
        title = "Pukara ES"
        weight = 1
        contentDir = "content/es"
    [languages.en]
        languageName = "en"
        baseURL = "https://pukara.es/en"
        weight = 2
        title = "Pukara EN"
        contentDir = "content/en"
    [languages.pt-br]
        languageName = "br"
        baseURL = "https://pukara.es/br"
        weight = 3
        title = "Pukara BR"
        contentDir = "content/br"

