baseURL = "https://pukaraes.github.io/pukaraes/"
languageCode = "es"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
title = "Pukara"
[languages]
    [languages.es]
        languageName = "Spanish"
        baseURL = "https://pukara.es/"
        title = "Pukara ES"
        weight = 1
		publishDir = "public/"
    [languages.en]
        languageName = "English"
        baseURL = "https://pukara.es/en"
        weight = 2
        title = "Pukara EN"
    [languages.br]
        languageName = "Portuguese"
        baseURL = "https://pukara.es/br"
        weight = 3
        title = "Pukara BR"

