baseURL = "https://pukaraes.github.io"
defaultContentLanguage = "es"
title = "Pukara"

[languages]
    [languages.es]
        languageName = "ES"
        baseURL = "https://pukaraes.github.io"
        title = "Pukara ES"
        weight = 1
        contentDir = "content/espanol"


    [languages.en]
        languageName = "EN"
        baseURL = "https://pukaraes.github.io/en"
        weight = 2
        title = "Pukara EN"
        contentDir = "content/english"

    [languages.pt-br]
        languageName = "BR"
        baseURL = "https://pukaraes.github.io/br"
        weight = 3
        title = "Pukara BR"
        contentDir = "content/portugues"

