baseURL = "https://pukaraes.github.io/pukaraes/es"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
title = "Pukara"
[languages]
    [languages.es]
        languageName = "Spanish"
        baseURL = "https://pukara.es/es"
        title = "Pukara ES"
        weight = 1
        contentDir = "content/es"
    [languages.en]
        languageName = "English"
        baseURL = "https://pukara.es/en"
        weight = 2
        title = "Pukara EN"
        contentDir = "content/en"
    [languages.pt-br]
        languageName = "Portuguese"
        baseURL = "https://pukara.es/br"
        weight = 3
        title = "Pukara BR"
        contentDir = "content/br"

