name: pukara develop deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Upload files on server.
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.dev.pukara.es
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: ./public_html/